service: redux-todo  # see https://cloud.google.com/appengine/docs/go/
runtime: go          # see https://cloud.google.com/appengine/docs/go/
api_version: go1     # used when appengine supports different go versions

# These are specified by using command line flag
# application: my-application-id  # defined when you create your app using google dev console
# version: alpha                  # you can run multiple versions of an app and A/B test

handlers:
- url: /api/.*
  script: _go_app

- url: /(active|completed)?
  static_files: ui/index.html
  upload: ui/index.html

- url: /(.*\.js)$
  static_files: ui/\1
  upload: ui/.*\.js$

nobuild_files:
- vendor/

skip_files:
- vendor/

env_variables:
  TRANSACTION_ATTEMPTS: '10'
